// <auto-generated />
using System;
using CivitaBack.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivitaBack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251126053721_ajustes_metricas")]
    partial class ajustes_metricas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivitaBack.Data.BO.CondicionEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreColumna")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.ToTable("Condicion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cantidad = 1,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstructuraId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cantidad = 1,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EstructuraId = 3
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EfectoEventoEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contaminacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Energia")
                        .HasColumnType("integer");

                    b.Property<int>("EventoMaestroId")
                        .HasColumnType("integer");

                    b.Property<int>("Experiencia")
                        .HasColumnType("integer");

                    b.Property<int>("Felicidad")
                        .HasColumnType("integer");

                    b.Property<int>("TipoResultado")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoMaestroId");

                    b.ToTable("EfectoEvento");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contaminacion = -4,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EcoCoins = 50,
                            Energia = 0,
                            EventoMaestroId = 1,
                            Experiencia = 50,
                            Felicidad = 3,
                            TipoResultado = 1
                        },
                        new
                        {
                            Id = 2,
                            Contaminacion = 3,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EcoCoins = -20,
                            Energia = 0,
                            EventoMaestroId = 1,
                            Experiencia = 0,
                            Felicidad = -2,
                            TipoResultado = 2
                        },
                        new
                        {
                            Id = 3,
                            Contaminacion = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EcoCoins = 0,
                            Energia = 0,
                            EventoMaestroId = 2,
                            Experiencia = 0,
                            Felicidad = 0,
                            TipoResultado = 1
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionCiclo")
                        .HasColumnType("integer");

                    b.Property<int>("CostoDinero")
                        .HasColumnType("integer");

                    b.Property<int>("CostoEnergia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsMejorable")
                        .HasColumnType("boolean");

                    b.Property<int>("FelicidadCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("text");

                    b.Property<int>("TipoEstructuraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoEstructuraId");

                    b.ToTable("Estructura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContaminacionCiclo = 1,
                            CostoDinero = 40,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 1,
                            Nombre = "Casa",
                            RutaImagen = "/Assets/mapa/Estructura-Edificio-3.png",
                            TipoEstructuraId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContaminacionCiclo = -2,
                            CostoDinero = 300,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = -1,
                            Nombre = "Turbina Eólica",
                            RutaImagen = "/Assets/mapa/Estructura-Molino.png",
                            TipoEstructuraId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContaminacionCiclo = 3,
                            CostoDinero = 50,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = -2,
                            Nombre = "Fábrica",
                            RutaImagen = "/Assets/mapa/Estructura-Fabrica-Nivel-1.png",
                            TipoEstructuraId = 3
                        },
                        new
                        {
                            Id = 4,
                            ContaminacionCiclo = 0,
                            CostoDinero = 30,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 1,
                            Nombre = "Parque",
                            RutaImagen = "/Assets/mapa/Estructura-Parque-Pequeño.png",
                            TipoEstructuraId = 4
                        },
                        new
                        {
                            Id = 5,
                            ContaminacionCiclo = 2,
                            CostoDinero = 150,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 2,
                            Nombre = "Hotel",
                            RutaImagen = "/Assets/mapa/Estructura-Hotel.png",
                            TipoEstructuraId = 5
                        },
                        new
                        {
                            Id = 6,
                            ContaminacionCiclo = -3,
                            CostoDinero = 400,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 3,
                            Nombre = "Planta Neocorp",
                            RutaImagen = "/Assets/mapa/Estructura-Fabrica-Nivel-2.png",
                            TipoEstructuraId = 6
                        },
                        new
                        {
                            Id = 7,
                            ContaminacionCiclo = -1,
                            CostoDinero = 80,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 0,
                            Nombre = "Panel solar",
                            RutaImagen = "/Assets/mapa/Estructura-Panel-Solar.png",
                            TipoEstructuraId = 7
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("PartidaId");

                    b.ToTable("EstructuraMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionAplicada")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoinsAplicada")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergiaAplicada")
                        .HasColumnType("integer");

                    b.Property<int>("EventoMaestroId")
                        .HasColumnType("integer");

                    b.Property<int>("ExperienciaAplicada")
                        .HasColumnType("integer");

                    b.Property<int>("FelicidadAplicada")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<string>("RespuestaJugador")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeDisparo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EventoMaestroId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContenidoPrincipal")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpcionA_Texto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("OpcionB_Texto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("RespuestaCorrecta")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("EventoMaestro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContenidoPrincipal = "Si tenés que recorrer 5 km en la ciudad, ¿qué opción genera la MENOR cantidad de emisiones de CO₂ (Dióxido de carbono) por persona?",
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpcionA_Texto = "A) Ir en colectivo con 30 personas más.",
                            OpcionB_Texto = "B) Usar un auto moderno, solo con el conductor.",
                            RespuestaCorrecta = "A",
                            TipoEvento = 1,
                            Titulo = "¿Cómo me muevo hoy?"
                        },
                        new
                        {
                            Id = 2,
                            ContenidoPrincipal = "Tu nivel de contaminación es críticamente alto. Si excede el 80%, la Felicidad de tus ciudadanos caerá rápidamente. Intentá construir más estructuras que limpien el aire y sumar espacios verdes.",
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpcionA_Texto = "Entendido.",
                            OpcionB_Texto = "",
                            RespuestaCorrecta = "A",
                            TipoEvento = 2,
                            Titulo = "¡Alerta Roja de Contaminación!"
                        },
                        new
                        {
                            Id = 3,
                            ContenidoPrincipal = "Tus reservas de energía están peligrosamente bajas. Si caen por debajo del 10%, varias estructuras dejarán de funcionar, afectando la Felicidad y el crecimiento de tu ciudad. Considerá construir más fuentes de energía renovable.",
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpcionA_Texto = "Entendido.",
                            OpcionB_Texto = "",
                            RespuestaCorrecta = "A",
                            TipoEvento = 2,
                            Titulo = "¡Alerta de Energía Crítica!"
                        },
                        new
                        {
                            Id = 4,
                            ContenidoPrincipal = "La Felicidad de tus ciudadanos está peligrosamente baja. Cuando esto ocurre, la población puede comenzar a disminuir y tu ciudad se vuelve menos estable. Revisá si hay suficiente refugio disponible y tratá de reducir los niveles de contaminación para mejorar el ánimo general de la población.",
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            OpcionA_Texto = "Entendido.",
                            OpcionB_Texto = "",
                            RespuestaCorrecta = "A",
                            TipoEvento = 2,
                            Titulo = "¡Felicidad en Nivel Crítico!"
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoLogroId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.HasIndex("TipoLogroId");

                    b.ToTable("Logro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartidaEF", b =>
                {
                    b.Property<int>("LogroId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LogroId", "PartidaId");

                    b.HasIndex("PartidaId");

                    b.ToTable("LogroPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.ToTable("Mision", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CondicionId = 1,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Nuestros ciudadanos necesitan lugar para vivir. Construí 1 casa.",
                            Disponible = true,
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Diaria",
                            Titulo = "¡Construye 1 casa!"
                        },
                        new
                        {
                            Id = 2,
                            CondicionId = 2,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "La ciudad necesita generar ingresos.",
                            Disponible = true,
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Tipo = "Diaria",
                            Titulo = "¡Construye 1 fabrica!"
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionPartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MisionId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Reclamado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.HasIndex("PartidaId");

                    b.ToTable("MisionPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstaPausada")
                        .HasColumnType("boolean");

                    b.Property<int>("Experiencia")
                        .HasColumnType("integer");

                    b.Property<string>("JsonMapa")
                        .HasColumnType("text");

                    b.Property<int>("Nivel")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimaVez")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecompensaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreColumna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.ToTable("Recompensa");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Cantidad = 50,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreColumna = "EcoCoins"
                        },
                        new
                        {
                            Id = 101,
                            Cantidad = 50,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreColumna = "Experiencia"
                        },
                        new
                        {
                            Id = 102,
                            Cantidad = 60,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreColumna = "Experiencia"
                        },
                        new
                        {
                            Id = 103,
                            Cantidad = 15,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreColumna = "Energia"
                        },
                        new
                        {
                            Id = 104,
                            Cantidad = 500,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Editado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreColumna = "EcoCoins"
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecursoEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contaminacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Energia")
                        .HasColumnType("integer");

                    b.Property<int>("Felicidad")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Poblacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TiendaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EfectoFiltro")
                        .HasColumnType("boolean");

                    b.Property<string>("ElementoAdicional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Expresion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Orden")
                        .HasColumnType("integer");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Tip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaSaluda",
                            Mensaje = "¡Hola!, soy Vita ",
                            Orden = 1,
                            TipoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "PulgarArribaVita",
                            Mensaje = "Te doy la bienvenida a Neocivita ",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaPregunta",
                            Mensaje = "Antes de empezar, ¿cómo te llamás?",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaExplica2",
                            Mensaje = "En Neocivita aprenderás sobre el impacto ecológico que tienen nuestras decisiones al construir y mantener una ciudad.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaDecidida",
                            Mensaje = "¿Creés que podés lograr el equilibrio entre economía, sociedad y ambiente?",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = true,
                            ElementoAdicional = "ecoCoinBrillante",
                            Expresion = "vitaExplica2",
                            Mensaje = "Estas son las EcoCoins, la moneda para adquirir construcciones en tu ciudad.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 7,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "ecoCoin",
                            Expresion = "vitaExplica",
                            Mensaje = "Podés conseguirlas con edificaciones industriales o completando misiones. ¡Acompañame a ver las demás!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 8,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "energiaCoin",
                            Expresion = "vitaCansada",
                            Mensaje = "Te presento la energía eléctrica: podés obtenerla con construcciones específicas que la generen, como un panel solar.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 9,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "contaminacionCoin",
                            Expresion = "vitaPensativa",
                            Mensaje = "Ahora… la CONTAMINACIÓN. Este recurso destruye tu ciudad y el planeta. ¡Tené cuidado!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 10,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "felicidadCoin",
                            Expresion = "vitaDecidida",
                            Mensaje = "La FELICIDAD refleja qué tan saludable y feliz está tu población. ¡Es muy importante!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 11,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaFesteja",
                            Mensaje = "Ahora que conocés los recursos del juego… ¡acompañame a jugar y empecemos a construir!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 12,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaFesteja",
                            Mensaje = "¡Registrate para empezar a construir nuestra ciudad!",
                            TipoId = 1
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("TipId");

                    b.ToTable("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructuraEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DineroPorCiclo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergiaPorCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ocupacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoEstructura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 5,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 1,
                            EnergiaPorCiclo = -1,
                            Nombre = "Vivienda",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -5,
                            EnergiaPorCiclo = 3,
                            Nombre = "Energia",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 10,
                            EnergiaPorCiclo = -2,
                            Nombre = "Industrial",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -2,
                            EnergiaPorCiclo = 1,
                            Nombre = "Verde",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacidad = 50,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 5,
                            EnergiaPorCiclo = -1,
                            Nombre = "Alojamiento",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -10,
                            EnergiaPorCiclo = 0,
                            Nombre = "Reciclaje",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -2,
                            EnergiaPorCiclo = 2,
                            Nombre = "Energia solar",
                            Ocupacion = 0
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoLogroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoTipEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TipoTip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "info"
                        },
                        new
                        {
                            Id = 2,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "onboarding"
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.UsuarioEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsDios")
                        .HasColumnType("boolean");

                    b.Property<string>("HashDeContrasena")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Mail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CondicionEFRecompensaEF", b =>
                {
                    b.Property<int>("CondicionesId")
                        .HasColumnType("integer");

                    b.Property<int>("RecompensasId")
                        .HasColumnType("integer");

                    b.HasKey("CondicionesId", "RecompensasId");

                    b.HasIndex("RecompensasId");

                    b.ToTable("CondicionRecompensa", (string)null);

                    b.HasData(
                        new
                        {
                            CondicionesId = 1,
                            RecompensasId = 100
                        },
                        new
                        {
                            CondicionesId = 1,
                            RecompensasId = 101
                        },
                        new
                        {
                            CondicionesId = 2,
                            RecompensasId = 103
                        },
                        new
                        {
                            CondicionesId = 2,
                            RecompensasId = 104
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.CondicionEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany()
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EfectoEventoEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EventoMaestroEF", "EventoMaestro")
                        .WithMany("Efectos")
                        .HasForeignKey("EventoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMaestro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoEstructuraEF", "TipoEstructura")
                        .WithMany("Estructura")
                        .HasForeignKey("TipoEstructuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEstructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany("EstructurasEnMapa")
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("EstructuraMapa")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estructura");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EventoMaestroEF", "EventoMaestro")
                        .WithMany("Evento")
                        .HasForeignKey("EventoMaestroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("Evento")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMaestro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.CondicionEF", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.TipoLogroEF", "TipoLogro")
                        .WithMany()
                        .HasForeignKey("TipoLogroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.LogroEF", "Logro")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.CondicionEF", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.MisionEF", "Mision")
                        .WithMany()
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("MisionPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mision");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.UsuarioEF", "Usuario")
                        .WithOne("Partida")
                        .HasForeignKey("CivitaBack.Data.BO.PartidaEF", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecompensaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany()
                        .HasForeignKey("EstructuraId");

                    b.Navigation("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecursoEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithOne("Recursos")
                        .HasForeignKey("CivitaBack.Data.BO.RecursoEF", "PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TiendaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany()
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("Tienda")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estructura");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoTipEF", "TipoTip")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoTip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.TipEF", "Tip")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("CondicionEFRecompensaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.CondicionEF", null)
                        .WithMany()
                        .HasForeignKey("CondicionesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.RecompensaEF", null)
                        .WithMany()
                        .HasForeignKey("RecompensasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.Navigation("EstructurasEnMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestroEF", b =>
                {
                    b.Navigation("Efectos");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.Navigation("LogroPartidas");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.Navigation("EstructuraMapa");

                    b.Navigation("Evento");

                    b.Navigation("LogroPartidas");

                    b.Navigation("MisionPartidas");

                    b.Navigation("Recursos");

                    b.Navigation("Tienda");

                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructuraEF", b =>
                {
                    b.Navigation("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.UsuarioEF", b =>
                {
                    b.Navigation("Partida")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
