// <auto-generated />
using System;
using CivitaBack.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivitaBack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251018141843_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivitaBack.Data.BO.Condicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<int>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<int>("RecursoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("RecursoId");

                    b.ToTable("Condicion");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Estructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionCiclo")
                        .HasColumnType("integer");

                    b.Property<int>("CostoDinero")
                        .HasColumnType("integer");

                    b.Property<int>("CostoEnergia")
                        .HasColumnType("integer");

                    b.Property<bool>("EsMejorable")
                        .HasColumnType("boolean");

                    b.Property<int>("FelicidadCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("text");

                    b.Property<int>("TipoEstructuraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoEstructuraId");

                    b.ToTable("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("PartidaId");

                    b.ToTable("EstructuraMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionEvento")
                        .HasColumnType("text");

                    b.Property<int>("EventoMaestroId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoParaHacerlo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventoMaestroId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EventoMaestro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Logro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoLogroId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.HasIndex("TipoLogroId");

                    b.ToTable("Logro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartida", b =>
                {
                    b.Property<int>("LogroId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.HasKey("LogroId", "PartidaId");

                    b.HasIndex("PartidaId");

                    b.ToTable("LogroPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("JsonMapa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaVez")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contaminacion")
                        .HasColumnType("integer");

                    b.Property<int>("EcoCoins")
                        .HasColumnType("integer");

                    b.Property<int>("Energia")
                        .HasColumnType("integer");

                    b.Property<int>("Felicidad")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Poblacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Tienda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoArticulo")
                        .HasColumnType("text");

                    b.Property<string>("NombreArticulo")
                        .HasColumnType("text");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EfectoFiltro")
                        .HasColumnType("boolean");

                    b.Property<string>("ElementoAdicional")
                        .HasColumnType("text");

                    b.Property<string>("Expresion")
                        .HasColumnType("text");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.Property<int?>("TipoTipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoTipId");

                    b.ToTable("Tip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("TipId");

                    b.ToTable("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<int>("DineroPorCiclo")
                        .HasColumnType("integer");

                    b.Property<int>("EnergiaPorCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasColumnType("text");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoEstructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoLogro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoTip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDeContrasena")
                        .HasColumnType("text");

                    b.Property<string>("Mail")
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Condicion", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Estructura", "Estructura")
                        .WithMany()
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estructura");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Estructura", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoEstructura", "TipoEstructura")
                        .WithMany("Estructura")
                        .HasForeignKey("TipoEstructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEstructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapa", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Estructura", "Estructura")
                        .WithMany("EstructurasEnMapa")
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithMany("EstructuraMapa")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estructura");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Evento", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EventoMaestro", "EventoMaestro")
                        .WithMany("Evento")
                        .HasForeignKey("EventoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithMany("Evento")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMaestro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Logro", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Condicion", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId");

                    b.HasOne("CivitaBack.Data.BO.TipoLogro", "TipoLogro")
                        .WithMany()
                        .HasForeignKey("TipoLogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartida", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Logro", "Logro")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Partida", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Usuario", "Usuario")
                        .WithOne("Partida")
                        .HasForeignKey("CivitaBack.Data.BO.Partida", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Recurso", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithOne("Recursos")
                        .HasForeignKey("CivitaBack.Data.BO.Recurso", "PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Tienda", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithMany("Tienda")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Tip", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoTip", "TipoTip")
                        .WithMany()
                        .HasForeignKey("TipoTipId");

                    b.Navigation("TipoTip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartida", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.Partida", "Partida")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.Tip", "Tip")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Estructura", b =>
                {
                    b.Navigation("EstructurasEnMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestro", b =>
                {
                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Logro", b =>
                {
                    b.Navigation("LogroPartidas");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Partida", b =>
                {
                    b.Navigation("EstructuraMapa");

                    b.Navigation("Evento");

                    b.Navigation("LogroPartidas");

                    b.Navigation("Recursos");

                    b.Navigation("Tienda");

                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Tip", b =>
                {
                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructura", b =>
                {
                    b.Navigation("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.Usuario", b =>
                {
                    b.Navigation("Partida")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
