// <auto-generated />
using System;
using CivitaBack.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivitaBack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivitaBack.Data.BO.CondicionEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsRecompensa")
                        .HasColumnType("boolean");

                    b.Property<int?>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreColumna")
                        .HasColumnType("text");

                    b.Property<int?>("RecompensaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("RecompensaId");

                    b.ToTable("Condicion");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionCiclo")
                        .HasColumnType("integer");

                    b.Property<int>("CostoDinero")
                        .HasColumnType("integer");

                    b.Property<int>("CostoEnergia")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsMejorable")
                        .HasColumnType("boolean");

                    b.Property<int>("FelicidadCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("text");

                    b.Property<int>("TipoEstructuraId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoEstructuraId");

                    b.ToTable("Estructura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContaminacionCiclo = 2,
                            CostoDinero = 25,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 2,
                            Nombre = "Casa",
                            RutaImagen = "/assets/mapa/casas.png",
                            TipoEstructuraId = 1
                        },
                        new
                        {
                            Id = 2,
                            ContaminacionCiclo = -4,
                            CostoDinero = 50,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 2,
                            Nombre = "Turbina Eólica",
                            RutaImagen = "/assets/mapa/turbina.png",
                            TipoEstructuraId = 2
                        },
                        new
                        {
                            Id = 3,
                            ContaminacionCiclo = 6,
                            CostoDinero = 40,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = -4,
                            Nombre = "Fabrica",
                            RutaImagen = "/assets/mapa/fabrica.png",
                            TipoEstructuraId = 3
                        },
                        new
                        {
                            Id = 4,
                            ContaminacionCiclo = 0,
                            CostoDinero = 0,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 0,
                            Nombre = "Iniciales",
                            TipoEstructuraId = 4
                        },
                        new
                        {
                            Id = 5,
                            ContaminacionCiclo = 0,
                            CostoDinero = 0,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 0,
                            Nombre = "InicialesCasa2",
                            TipoEstructuraId = 5
                        },
                        new
                        {
                            Id = 6,
                            ContaminacionCiclo = 0,
                            CostoDinero = 0,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 0,
                            Nombre = "InicialesEdificio",
                            TipoEstructuraId = 6
                        },
                        new
                        {
                            Id = 7,
                            ContaminacionCiclo = 0,
                            CostoDinero = 0,
                            CostoEnergia = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EsMejorable = false,
                            FelicidadCiclo = 0,
                            Nombre = "InicialesBase",
                            TipoEstructuraId = 7
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstructuraId")
                        .HasColumnType("integer");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.Property<int>("X")
                        .HasColumnType("integer");

                    b.Property<int>("Y")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EstructuraId");

                    b.HasIndex("PartidaId");

                    b.ToTable("EstructuraMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionAceptar")
                        .HasColumnType("integer");

                    b.Property<int>("ContaminacionRechazar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoinsAceptar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventoMaestroId")
                        .HasColumnType("integer");

                    b.Property<int>("FelicidadAceptar")
                        .HasColumnType("integer");

                    b.Property<int>("FelicidadRechazar")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("boolean");

                    b.Property<bool>("SeDisparo")
                        .HasColumnType("boolean");

                    b.Property<string>("TextoAceptar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TextoDescripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextoRechazar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventoMaestroId");

                    b.HasIndex("PartidaId");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContaminacionAceptar")
                        .HasColumnType("integer");

                    b.Property<int>("ContaminacionRechazar")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoinsAceptar")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FelicidadAceptar")
                        .HasColumnType("integer");

                    b.Property<int>("FelicidadRechazar")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TextoAceptar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TextoDescripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TextoRechazar")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("EventoMaestro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TipoLogroId")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.HasIndex("TipoLogroId");

                    b.ToTable("Logro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartidaEF", b =>
                {
                    b.Property<int>("LogroId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LogroId", "PartidaId");

                    b.HasIndex("PartidaId");

                    b.ToTable("LogroPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CondicionId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CondicionId");

                    b.ToTable("Mision", (string)null);
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionPartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCompletado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MisionId")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<bool>("Reclamado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MisionId");

                    b.HasIndex("PartidaId");

                    b.ToTable("MisionPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonMapa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimaVez")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecursoEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contaminacion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EcoCoins")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Energia")
                        .HasColumnType("integer");

                    b.Property<int>("Felicidad")
                        .HasColumnType("integer");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("Poblacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId")
                        .IsUnique();

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TiendaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoArticulo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreArticulo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Tienda");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EfectoFiltro")
                        .HasColumnType("boolean");

                    b.Property<string>("ElementoAdicional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Expresion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TipoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TipoId");

                    b.ToTable("Tip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaSaluda",
                            Mensaje = "¡Hola!, soy Vita ",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 2,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "PulgarArribaVita",
                            Mensaje = "Te doy la bienvenida a Neocivita ",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 3,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaPregunta",
                            Mensaje = "Antes de empezar, ¿cómo te llamás?",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 4,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaExplica2",
                            Mensaje = "En Neocivita aprenderás sobre el impacto ecológico que tienen nuestras decisiones al construir y mantener una ciudad.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 5,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaDecidida",
                            Mensaje = "¿Creés que podés lograr el equilibrio entre economía, sociedad y ambiente?",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 6,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = true,
                            ElementoAdicional = "ecoCoinBrillante",
                            Expresion = "vitaExplica2",
                            Mensaje = "Estas son las EcoCoins, la moneda para adquirir construcciones en tu ciudad.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 7,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "ecoCoin",
                            Expresion = "vitaExplica",
                            Mensaje = "Podés conseguirlas con edificaciones industriales o completando misiones. ¡Acompañame a ver las demás!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 8,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "energiaCoin",
                            Expresion = "vitaCansada",
                            Mensaje = "Te presento la energía eléctrica: podés obtenerla con construcciones específicas que la generen, como un panel solar.",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 9,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "contaminacionCoin",
                            Expresion = "vitaPensativa",
                            Mensaje = "Ahora… la CONTAMINACIÓN. Este recurso destruye tu ciudad y el planeta. ¡Tené cuidado!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 10,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "felicidadCoin",
                            Expresion = "vitaDecidida",
                            Mensaje = "La FELICIDAD refleja qué tan saludable y feliz está tu población. ¡Es muy importante!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 11,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaFesteja",
                            Mensaje = "Ahora que conocés los recursos del juego… ¡acompañame a jugar y empecemos a construir!",
                            TipoId = 1
                        },
                        new
                        {
                            Id = 12,
                            Creado = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EfectoFiltro = false,
                            ElementoAdicional = "",
                            Expresion = "vitaFesteja",
                            Mensaje = "¡Registrate para empezar a construir nuestra ciudad!",
                            TipoId = 1
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartidaEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PartidaId")
                        .HasColumnType("integer");

                    b.Property<int>("TipId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PartidaId");

                    b.HasIndex("TipId");

                    b.ToTable("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructuraEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DineroPorCiclo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnergiaPorCiclo")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Ocupacion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TipoEstructura");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -3,
                            EnergiaPorCiclo = -2,
                            Nombre = "Vivienda",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 2,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = -7,
                            EnergiaPorCiclo = 10,
                            Nombre = "Energia",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 3,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 50,
                            EnergiaPorCiclo = -4,
                            Nombre = "Industrial",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 4,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 0,
                            EnergiaPorCiclo = 0,
                            Nombre = "Inicial",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 5,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 0,
                            EnergiaPorCiclo = 0,
                            Nombre = "InicialCasa2",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 6,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 0,
                            EnergiaPorCiclo = 0,
                            Nombre = "InicialEdificio",
                            Ocupacion = 0
                        },
                        new
                        {
                            Id = 7,
                            Capacidad = 0,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DineroPorCiclo = 0,
                            EnergiaPorCiclo = 0,
                            Nombre = "InicialBase",
                            Ocupacion = 0
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoLogroEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoTipEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("TipoTip");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "info"
                        },
                        new
                        {
                            Id = 2,
                            Creado = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "onboarding"
                        });
                });

            modelBuilder.Entity("CivitaBack.Data.BO.UsuarioEF", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Editado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HashDeContrasena")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Mail")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.CondicionEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany()
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CivitaBack.Data.BO.CondicionEF", "Recompensa")
                        .WithMany("CondicionesAsociadas")
                        .HasForeignKey("RecompensaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Estructura");

                    b.Navigation("Recompensa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoEstructuraEF", "TipoEstructura")
                        .WithMany("Estructura")
                        .HasForeignKey("TipoEstructuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoEstructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraMapaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EstructuraEF", "Estructura")
                        .WithMany("EstructurasEnMapa")
                        .HasForeignKey("EstructuraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("EstructuraMapa")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estructura");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.EventoMaestroEF", "EventoMaestro")
                        .WithMany("Evento")
                        .HasForeignKey("EventoMaestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("Evento")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventoMaestro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.CondicionEF", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.TipoLogroEF", "TipoLogro")
                        .WithMany()
                        .HasForeignKey("TipoLogroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condicion");

                    b.Navigation("TipoLogro");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.LogroEF", "Logro")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("LogroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("LogroPartidas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Logro");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.CondicionEF", "Condicion")
                        .WithMany()
                        .HasForeignKey("CondicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Condicion");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.MisionPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.MisionEF", "Mision")
                        .WithMany()
                        .HasForeignKey("MisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mision");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.UsuarioEF", "Usuario")
                        .WithOne("Partida")
                        .HasForeignKey("CivitaBack.Data.BO.PartidaEF", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.RecursoEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithOne("Recursos")
                        .HasForeignKey("CivitaBack.Data.BO.RecursoEF", "PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TiendaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("Tienda")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.TipoTipEF", "TipoTip")
                        .WithMany()
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoTip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEnPartidaEF", b =>
                {
                    b.HasOne("CivitaBack.Data.BO.PartidaEF", "Partida")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CivitaBack.Data.BO.TipEF", "Tip")
                        .WithMany("TipEnPartida")
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partida");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.CondicionEF", b =>
                {
                    b.Navigation("CondicionesAsociadas");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EstructuraEF", b =>
                {
                    b.Navigation("EstructurasEnMapa");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.EventoMaestroEF", b =>
                {
                    b.Navigation("Evento");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.LogroEF", b =>
                {
                    b.Navigation("LogroPartidas");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.PartidaEF", b =>
                {
                    b.Navigation("EstructuraMapa");

                    b.Navigation("Evento");

                    b.Navigation("LogroPartidas");

                    b.Navigation("Recursos");

                    b.Navigation("Tienda");

                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipEF", b =>
                {
                    b.Navigation("TipEnPartida");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.TipoEstructuraEF", b =>
                {
                    b.Navigation("Estructura");
                });

            modelBuilder.Entity("CivitaBack.Data.BO.UsuarioEF", b =>
                {
                    b.Navigation("Partida")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
