<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>285a7653-2294-4df0-ace1-003f35837d51</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\20251018141843_test.cs" />
    <Compile Remove="Migrations\20251018141843_test.Designer.cs" />
    <Compile Remove="Migrations\20251018153035_test.cs" />
    <Compile Remove="Migrations\20251018153035_test.Designer.cs" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="8.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\CivitaBack.Domain\CivitaBack.Domain.csproj" />
	  <ProjectReference Include="..\CivitaBack.Utils\CivitaBack.Utils.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Interfaces\" />
	</ItemGroup>

</Project>
