name: CI - Build .NET API

on:
  push:
    branches: [desarrollo]
  pull_request:
    branches: [desarrollo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧭 Checkout repository
        uses: actions/checkout@v4

      - name: 🧰 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x" # o la versión que uses (7.0, etc.)

      - name: 📦 Restore dependencies
        run: dotnet restore

      - name: 🏗️ Build project
        run: dotnet build --configuration Release --no-restore
